"""Phase 24 provider interface. All adapters return canonical-out only."""
from typing import Protocol

class BlockchainProvider(Protocol):
    def get_transactions(self, address: str) -> list[dict]: ...
    def get_address_labels(self, address: str) -> list[dict]: ...
    def get_token_transfers(self, address: str) -> list[dict]: ...
    def get_block(self, height: int) -> dict: ...
